# fly.toml file generated for blimdam on 2022-12-11T17:55:02+01:00

app = "blimdam"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true
